Update log4j.properties.epp
voxpupuli/puppet-kafka pull request #339
Opened 2022-11-11 16:28 UTC by Kumar-Test

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2022-11-11 18:10 UTC, Kumar-Test commented
@bastelfreak  could you please have a look?

2022-11-12 17:12 UTC, kenyon requested changes
`${log_dir}` won't be replaced with its value unless it's in EPP templating delimiters `<%= %>`, and the variable is passed to the template in the `epp()` function, or the variable is fully-qualified. Also we need #336 so that the tests pass.

2022-11-13 10:32 UTC, Kumar-Test commented
@kenyon Thank for you review, i have done the requested changes , could you please review it?

2022-11-13 15:52 UTC, kenyon requested changes
Still won't work. `epp('kafka/log4j.properties.epp', ...` needs the log_dir variable added.

2022-11-13 16:08 UTC, Kumar-Test commented
@kenyon done, please have a look.

2022-11-13 16:13 UTC, kenyon reviewed
Should be OK now, but we need #336 done so that tests pass. Also would be good to have this log_dir change covered by tests.

2024-04-17 17:23 UTC, kenyon requested changes
Has merge conflicts that need to be resolved.

2026-01-03 10:31 UTC, TheMeier commented
@Kumar-Test do you still care about this?

2026-02-18 18:41 UTC, TheMeier commented
I am closing this due to lack of activity.

2026-02-18 18:41 UTC, closed without merging